In [1]:
import torch

In [6]:
t1 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.Tensor([[4, 5, 7], [6, 5, 4]])

In [8]:
t1+t2

tensor([[ 5.,  7., 10.],
        [10., 10., 10.]])

In [9]:
2*t1

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [10]:
t1*t2

tensor([[ 4., 10., 21.],
        [24., 25., 24.]])

In [4]:
t2

tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]])