In [1]:
import torch

In [25]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [26]:
X

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

visualizziamo lo stride

lo stride definisce la spaziatura tra gli elementi di un tensore lungo una dimensione specifica, di fatto definisce quando andare a capo in un tensore

In [27]:
X.stride()

(3, 1)

creiamo un nuovo tensore basandoci su uno stride nuovo

In [28]:
X

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
torch.as_strided(X, (2, 2), (1, 2))

tensor([[1, 3],
        [2, 4]])

In [ ]:
torch.as_strided(X, (3, 3), (1, 3)) # calcolata la trasposta con lo stride

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [30]:
def transpose_with_stride(X):
    return torch.as_strided(X, (X.shape[1], X.shape[0]), (1, X.shape[1]))

In [32]:
transpose_with_stride(torch.tensor([[1, 2, 3,4,5], [6,7,8,9,10], [11,12,13,14,15]]))

tensor([[ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14],
        [ 5, 10, 15]])

la funzione contiguous restituisce lo stesso tensore ma contiguo in memoria, con vantaggi su efficienza

In [34]:
X.contiguous()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

torch.reshape: torna un tensore con gli stessi dati ma con la shape modificata

torch.view: come reshape ma opera su tensori contigui

In [37]:
X.view((9))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
try:
  torch.reshape(X, (9))
except Exception as e:
  print(e)

reshape(): argument 'shape' (position 2) must be tuple of ints, not int


In [40]:
X.view((3,3))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
torch.reshape(X, (3,3))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
X.view(3,-1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
torch.reshape(X, (3,-1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
X.view((9,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [43]:
torch.reshape(X, (9,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

controllo se la gpu è disponibile e se si stampo il ome della prima gpu

In [54]:
if torch.cuda.is_available():
  torch.cuda.get_device_name(0)
else:
  print("No GPU found")

No GPU found


creo il device gpu se questa è disponibile

In [55]:
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'


In [57]:
device

'cpu'

In [59]:
tensor_to_device = torch.Tensor([[1,2,3],[4,5,6]]).to(device)
tensor_to_device

tensor([[1., 2., 3.],
        [4., 5., 6.]])

vedo il device corrente

In [60]:
tensor_to_device.device

device(type='cpu')